import io
from datetime import datetime
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from app.database import get_db
from app.models import Article, GovernanceRiskScore, Alert, DetectionResult, SentimentRecord


router = APIRouter(prefix="/api", tags=["Reports"])


def _build_text_report(db: Session) -> str:
    """Generate a comprehensive governance report as formatted text."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Stats
    total = db.query(func.count(Article.id)).scalar() or 0
    avg_gri = db.query(func.avg(GovernanceRiskScore.gri_score)).scalar() or 0
    max_gri = db.query(func.max(GovernanceRiskScore.gri_score)).scalar() or 0
    fake = db.query(func.count(DetectionResult.id)).filter(DetectionResult.label == "FAKE").scalar() or 0
    active_alerts = db.query(func.count(Alert.id)).filter(Alert.is_active == True).scalar() or 0
    critical_alerts = db.query(func.count(Alert.id)).filter(Alert.severity == "CRITICAL", Alert.is_active == True).scalar() or 0
    avg_anger = db.query(func.avg(SentimentRecord.anger_rating)).scalar() or 0

    # Category breakdown
    cats = (
        db.query(Article.category, func.count(Article.id), func.avg(GovernanceRiskScore.gri_score))
        .join(GovernanceRiskScore, GovernanceRiskScore.article_id == Article.id)
        .group_by(Article.category)
        .order_by(func.avg(GovernanceRiskScore.gri_score).desc())
        .all()
    )

    # Location breakdown
    locs = (
        db.query(Article.location, func.count(Article.id), func.avg(GovernanceRiskScore.gri_score))
        .join(GovernanceRiskScore, GovernanceRiskScore.article_id == Article.id)
        .group_by(Article.location)
        .order_by(func.avg(GovernanceRiskScore.gri_score).desc())
        .all()
    )

    # Top 10 risks
    top_risks = (
        db.query(Article, GovernanceRiskScore, DetectionResult)
        .join(GovernanceRiskScore, GovernanceRiskScore.article_id == Article.id)
        .join(DetectionResult, DetectionResult.article_id == Article.id)
        .order_by(GovernanceRiskScore.gri_score.desc())
        .limit(10)
        .all()
    )

    # Active alerts
    alerts = (
        db.query(Alert, Article)
        .join(Article, Article.id == Alert.article_id)
        .filter(Alert.is_active == True)
        .order_by(Alert.severity.desc())
        .limit(15)
        .all()
    )

    sep = "=" * 72
    line = "-" * 72

    report = f"""
{sep}
   GOVERNANCE INTELLIGENCE REPORT
   Predictive Risk Assessment & Decision Support
{sep}
   Generated: {now}
   System: Governance Intelligence DSS v1.0
{sep}

1. EXECUTIVE SUMMARY
{line}
   Total Signals Processed:    {total}
   Governance Risk Index (Avg): {avg_gri:.1f} / 100
   Highest GRI Score:          {max_gri:.1f}
   Fake News Detected:         {fake} ({round(fake/max(total,1)*100, 1)}%)
   Active Alerts:              {active_alerts} (Critical: {critical_alerts})
   Average Anger Rating:       {avg_anger:.1f} / 10

2. RISK ASSESSMENT BY CATEGORY
{line}
{"   Category":<30} {"Signals":>8} {"Avg GRI":>10} {"Risk Level":>12}
{line}
"""
    for cat, count, agri in cats:
        level = "HIGH" if (agri or 0) > 60 else "MODERATE" if (agri or 0) > 30 else "LOW"
        report += f"   {cat:<28} {count:>8} {agri:>10.1f} {level:>12}\n"

    report += f"""
3. RISK ASSESSMENT BY LOCATION
{line}
{"   Location":<30} {"Signals":>8} {"Avg GRI":>10} {"Risk Level":>12}
{line}
"""
    for loc, count, agri in locs:
        level = "HIGH" if (agri or 0) > 60 else "MODERATE" if (agri or 0) > 30 else "LOW"
        report += f"   {loc:<28} {count:>8} {agri:>10.1f} {level:>12}\n"

    report += f"""
4. TOP 10 PRIORITY RISKS
{line}
"""
    for i, (a, g, d) in enumerate(top_risks, 1):
        report += f"""   #{i}. {a.title}
       Location: {a.location} | Category: {a.category}
       GRI: {g.gri_score:.0f} | Veracity: {d.label} | Confidence: {d.confidence_score:.0%}
"""

    report += f"""
5. ACTIVE ALERTS & RECOMMENDATIONS
{line}
"""
    for alert, article in alerts:
        report += f"""   [{alert.severity}] {article.title}
       Department: {alert.department}
       Recommendation: {alert.recommendation}
       Urgency: {alert.urgency}
       Response: {alert.response_strategy}
"""

    report += f"""
{sep}
   END OF REPORT
   This report was auto-generated by the Governance Intelligence DSS.
   For questions, contact the system administrator.
{sep}
"""
    return report


@router.get("/report/download")
def download_report(db: Session = Depends(get_db)):
    """Generate and download a governance intelligence report."""
    report_text = _build_text_report(db)
    buffer = io.BytesIO(report_text.encode("utf-8"))
    buffer.seek(0)

    filename = f"governance_report_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.txt"

    return StreamingResponse(
        buffer,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/report/preview")
def preview_report(db: Session = Depends(get_db)):
    """Preview the report content as JSON."""
    total = db.query(func.count(Article.id)).scalar() or 0
    avg_gri = db.query(func.avg(GovernanceRiskScore.gri_score)).scalar() or 0
    fake = db.query(func.count(DetectionResult.id)).filter(DetectionResult.label == "FAKE").scalar() or 0
    active_alerts = db.query(func.count(Alert.id)).filter(Alert.is_active == True).scalar() or 0

    return {
        "summary": {
            "total_signals": total,
            "avg_gri": round(avg_gri, 1),
            "fake_news": fake,
            "active_alerts": active_alerts,
        },
        "download_url": "/api/report/download",
    }
